[package]
name = "askama_fuzzing"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
fuzz = { path = "fuzz" }

arbitrary = "1.4.1"
pretty-error-debug = "0.3.0"
thiserror = "2.0.3"

[profile.release]
debug = 1

[workspace]
members = [".", "fuzz"]
