version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "bench-build"
      - "examples/*"
      - "fuzzing"
      - "fuzzing/fuzz"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "testing/jinja2-assumptions"
    schedule:
      interval: "weekly"
