[package]
name = "rinja"
version = "0.2.0"
description = "Type-safe, compiled Jinja-like templates for Rust"
documentation = "https://docs.rs/rinja"
keywords = ["markup", "template", "jinja2", "html"]
categories = ["template-engine"]
homepage = "https://rinja.readthedocs.io/"
repository = "https://github.com/rinja-rs/rinja"
license = "MIT OR Apache-2.0"
workspace = ".."
readme = "../README.md"
edition = "2021"
rust-version = "1.71"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["config", "humansize", "num-traits", "urlencode"]
config = ["rinja_derive/config"]
humansize = ["rinja_derive/humansize", "dep:humansize"]
num-traits = ["rinja_derive/num-traits", "dep:num-traits"]
serde_json = ["rinja_derive/serde_json", "dep:serde", "dep:serde_json"]
urlencode = ["rinja_derive/urlencode", "dep:percent-encoding"]

# Please do not depend on the following features manually.
# Depend on the relevant integration crate instead!
with-actix-web = ["rinja_derive/with-actix-web"]
with-axum = ["rinja_derive/with-axum"]
with-rocket = ["rinja_derive/with-rocket"]
with-warp = ["rinja_derive/with-warp"]

[dependencies]
rinja_derive = { version = "0.2.0", path = "../rinja_derive" }

itoa = "1.0.11"

humansize = { version = "2", optional = true }
num-traits = { version = "0.2.6", optional = true }
percent-encoding = { version = "2.1.0", optional = true }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
jetscii = "0.5.3"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "to-json"
harness = false
required-features = ["serde_json"]

[[bench]]
name = "escape"
harness = false

[package.metadata.docs.rs]
features = ["default", "serde_json"]
rustdoc-args = ["--generate-link-to-definition", "--cfg=docsrs"]
